export const DEFAULT_SETTINGS = Object.freeze({homeArea:"Johnstons River, PEI",marketRegion:"Prince Edward Island, Canada",preferredAreas:"Stratford, Charlottetown, Cornwall",radiusCentre:"Charlottetown",radiusKm:70,vehicle:"Nissan Rogue, rear seats fold down",minimumProfit:40,targetProfit:60,minimumHourly:25,targetHourly:35,maxInvestment:100,riskLevel:"Balanced",currency:"CAD",showExamples:true});
export const SOURCES=["Facebook Marketplace","Kijiji","Thrift store","Yard or garage sale","Estate sale","Auction","Flea market","Curbside or free listing","ReStore","Clearance or liquidation","Surplus sale","Other"];
export const STAGES=["Considering","Seller Contacted","Inspection Needed","Passed","Purchased or Picked Up","Cleaning","Repairing","Ready for Photos","Ready to List","Listed","Offer Received","Sold","Donated","Parted Out","Abandoned"];
const CLOSED_STAGES=new Set(["Sold","Donated","Parted Out","Abandoned"]);
export function numberValue(value,fallback=0){const cleaned=typeof value==="string"?value.replace(/CAD/gi,"").replaceAll(",","").replaceAll("$","").trim():value;const parsed=typeof cleaned==="number"?cleaned:Number.parseFloat(cleaned);return Number.isFinite(parsed)?parsed:fallback;}
export function formatMoney(value){return new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD",maximumFractionDigits:0}).format(numberValue(value));}
export function formatPercent(value){return Number.isFinite(value)?`${Math.round(value)}%`:"—";}
export function createId(prefix="item"){if(globalThis.crypto?.randomUUID)return `${prefix}-${globalThis.crypto.randomUUID()}`;return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
export function isClosedStage(stage){return CLOSED_STAGES.has(stage);}
export function daysBetween(start,end=new Date()){const d=new Date(start);return Number.isNaN(d.getTime())?0:Math.max(0,Math.floor((end.getTime()-d.getTime())/86400000));}
function confidenceLevel(value){const v=String(value||"low").toLowerCase();return v.startsWith("high")?"high":v.startsWith("medium")?"medium":"low";}
export function calculateFinancials(item){const a=item.analysis||{};const askingPrice=numberValue(item.askingPrice);const hasPurchasePrice=item.purchasePrice!==""&&item.purchasePrice!==null&&item.purchasePrice!==undefined;const purchasePrice=hasPurchasePrice?numberValue(item.purchasePrice):askingPrice;const recordedExpenses=(item.expenses||[]).reduce((s,e)=>s+numberValue(e.amount),0);const plannedCosts=numberValue(a.cleaningCost)+numberValue(a.repairCost)+numberValue(a.transportCost)+numberValue(a.platformFees);const expectedInvestment=purchasePrice+Math.max(plannedCosts,recordedExpenses);const actualInvestment=purchasePrice+recordedExpenses;const asIsLow=numberValue(a.asIsLow),asIsHigh=numberValue(a.asIsHigh),improvedLow=numberValue(a.improvedLow),improvedHigh=numberValue(a.improvedHigh);const improved=improvedLow>0&&improvedHigh>0;const resaleLow=improved?improvedLow:asIsLow,resaleHigh=improved?improvedHigh:asIsHigh,resaleMid=resaleLow&&resaleHigh?(resaleLow+resaleHigh)/2:resaleLow||resaleHigh;const estimatedHours=Math.max(numberValue(a.estimatedHours,numberValue(item.hoursSpent)),0);const expectedNetLow=resaleLow-expectedInvestment,expectedNetMid=resaleMid-expectedInvestment,expectedProfitPerHour=estimatedHours>0?expectedNetLow/estimatedHours:null;const salePrice=numberValue(item.salePrice);const actualNet=salePrice>0?salePrice-actualInvestment:null;const actualProfitPerHour=actualNet!==null&&numberValue(item.hoursSpent)>0?actualNet/numberValue(item.hoursSpent):null;const expectedRoi=expectedInvestment>0?expectedNetLow/expectedInvestment*100:null;const actualRoi=actualNet!==null&&actualInvestment>0?actualNet/actualInvestment*100:null;return{askingPrice,purchasePrice,recordedExpenses,plannedCosts,expectedInvestment,actualInvestment,resaleLow,resaleHigh,resaleMid,expectedNetLow,expectedNetMid,expectedProfitPerHour,expectedRoi,salePrice,actualNet,actualProfitPerHour,actualRoi};}
export function personalizedDecision(item,settings=DEFAULT_SETTINGS){if(!item.analysis)return{verdict:"Research Further",tone:"research",reason:"Run the AI evaluation before spending money."};const a=item.analysis,f=calculateFinancials(item),confidence=confidenceLevel(a.confidence),minProfit=numberValue(settings.minimumProfit,40),targetProfit=numberValue(settings.targetProfit,60),minHourly=numberValue(settings.minimumHourly,25),targetHourly=numberValue(settings.targetHourly,35),maxInvestment=numberValue(settings.maxInvestment,100),riskText=`${a.biggestRisk||""} ${(a.safetyConcerns||[]).join(" ")}`.toLowerCase();if(/mould|mold|bed bug|pest infestation|unsafe|fire hazard|asbestos|stolen|structural failure|recall/.test(riskText))return{verdict:"Avoid",tone:"avoid",reason:"A safety, contamination, recall or structural risk could wipe out the profit."};if(f.expectedInvestment>maxInvestment)return{verdict:f.askingPrice>0?"Negotiate":"Research Further",tone:"negotiate",reason:`Total expected investment is above your ${formatMoney(maxInvestment)} limit.`};if(f.expectedNetLow<0)return{verdict:"Avoid",tone:"avoid",reason:"The conservative resale estimate loses money after expected costs."};if(f.expectedNetLow<minProfit)return f.askingPrice<=0?{verdict:"Take Only If Free",tone:"free",reason:`Conservative profit is below your ${formatMoney(minProfit)} minimum.`}:{verdict:"Negotiate",tone:"negotiate",reason:`Conservative profit is below your ${formatMoney(minProfit)} minimum. Lower the buy price.`};if(f.expectedProfitPerHour!==null&&f.expectedProfitPerHour<minHourly)return{verdict:"Negotiate",tone:"negotiate",reason:`Estimated return is below your ${formatMoney(minHourly)}/hour minimum.`};if(confidence==="low")return{verdict:"Research Further",tone:"research",reason:"The AI is not confident enough to risk your money yet. Get the model, condition and comparable-sale evidence."};if(f.askingPrice<=0&&f.expectedNetLow>=targetProfit)return{verdict:"Pick Up Immediately",tone:"buy",reason:`It is free and clears your ${formatMoney(targetProfit)} preferred profit target.`};if(f.expectedNetLow>=targetProfit&&(f.expectedProfitPerHour===null||f.expectedProfitPerHour>=targetHourly))return{verdict:"Buy",tone:"buy",reason:`It clears your ${formatMoney(targetProfit)} profit and ${formatMoney(targetHourly)}/hour preferred targets.`};return{verdict:"Negotiate",tone:"negotiate",reason:"The flip may work, but your margin is not strong enough at the current price."};}
function cleanText(value,fallback="Not provided"){const text=String(value??"").trim();return text||fallback;}
export function buildAnalysisPrompt(item,settings=DEFAULT_SETTINGS){return `You are Flip Finder AI, a practical resale-flipping assistant for one Canadian user. Analyze the attached item photos and listing information. Work with ANY category. Never pretend an uncertain identification, value, age, material, brand, model or condition is confirmed.

USER RULES
Market: ${cleanText(settings.marketRegion)}
Preferred areas: ${cleanText(settings.preferredAreas)}
Search radius: ${numberValue(settings.radiusKm,70)} km from ${cleanText(settings.radiusCentre,"Charlottetown")}
Transport: ${cleanText(settings.vehicle)}
Minimum net profit: ${formatMoney(settings.minimumProfit)}
Preferred net profit: ${formatMoney(settings.targetProfit)}
Minimum profit per hour: ${formatMoney(settings.minimumHourly)}
Preferred profit per hour: ${formatMoney(settings.targetHourly)}
Maximum total investment: ${formatMoney(settings.maxInvestment)}
Risk: ${cleanText(settings.riskLevel)}

LISTING
Source: ${cleanText(item.source)}
Asking price: ${formatMoney(item.askingPrice)}
Location: ${cleanText(item.location)}
Description: ${cleanText(item.sellerDescription)}
Brand/model: ${cleanText([item.brand,item.model].filter(Boolean).join(" "))}
Dimensions: ${cleanText(item.dimensions)}
Condition notes: ${cleanText(item.conditionNotes)}
Question: ${cleanText(item.question,"Is this worth flipping?")}

RULES
1. Separate visible facts, likely possibilities and must-verify checks.
2. Look for labels, model numbers, markings, material, construction, damage, missing parts, moisture, mould, pests, rust, cracks, stains and safety issues.
3. Use conservative local used-market estimates, not retail or antique-store asking prices. Never invent sold comparables.
4. Normal local cash Marketplace/Kijiji platform fee = 0 unless the user supplies a real fee. Do not invent fees.
5. Transport cost = 0 unless a real distance/cost is supplied. Do not invent fuel costs.
6. The app calculates the final buy decision. Do not override its profit rules.
7. Recommend only low-cost improvements where likely added value exceeds cost. Preserve labels, finishes, patina and collectible features.
8. Avoid unsafe electrical, structural, mould-remediation or professional restoration instructions.
9. Do not hide defects or create misleading listing photos.
10. Return JSON only.

JSON FORMAT
{"suggestedName":"","category":"","likelyUse":"","visibleFacts":[],"likelyPossibilities":[],"verifyInPerson":[],"condition":"","valueFeatures":[],"safetyConcerns":[],"openingOffer":0,"maxPurchasePrice":0,"asIsLow":0,"asIsHigh":0,"improvedLow":0,"improvedHigh":0,"cleaningCost":0,"repairCost":0,"transportCost":0,"platformFees":0,"estimatedHours":0,"timeToSell":"","confidence":"Low, Medium or High","mainReason":"","biggestRisk":"","bestStrategy":"","nextStep":"","summary":""}`;}
export const QUICK_ACTIONS=[["worth","Is It Worth Buying?"],["identify","Identify This Item"],["inspect","What Should I Check?"],["max-price","Maximum Price to Pay"],["seller-message","Write Seller Message"],["clean","Create Cleaning Plan"],["repair","Create Repair Plan"],["supplies","Make Supply List"],["photos","Photo Instructions"],["listing","Write Listing"],["buyer-reply","Respond to Buyer"],["offer","Evaluate Offer"],["lower-price","Should I Lower the Price?"],["profit","Calculate Final Profit"]];
const ACTION_REQUESTS={worth:"Give one clear verdict using my saved profit rules. Show asking price, realistic resale, expected costs, conservative net profit and the price I should actually pay.",identify:"Identify the item from the photos. Separate visible facts, likely possibilities and must-verify information. Look for model numbers and labels.",inspect:"Create a short category-specific inspection checklist. Put safety, completeness and profit-killing defects first.","max-price":"Calculate a conservative maximum purchase price using my minimum profit and hourly targets. Do not use a higher AI guess if it conflicts with my rules.","seller-message":"Write one short natural message asking only the most important unanswered questions before I travel to see the item.",clean:"Create a low-cost cleaning plan with supplies, cost, time and safety. Protect original finish, labels and patina.",repair:"Create a low-cost repair plan only where expected value increase exceeds cost. Clearly mark anything I should not attempt myself.",supplies:"Give me the smallest inexpensive supply list for worthwhile work. Avoid specialized tools unless the item justifies them.",photos:"Give exact iPhone product-photo instructions for an honest listing: setup, light, angles, detail shots, measurements and defects.",listing:"Write an honest Facebook Marketplace/Kijiji listing. Include title, description, condition, measurements, defects, included parts, asking price, lowest acceptable price and photo order. Do not publish it.","buyer-reply":"Write a short natural reply to the buyer message I provide. Protect my minimum acceptable price and do not promise a hold unless I approve it.",offer:"Evaluate the buyer offer against my actual investment and saved profit rules. Recommend accept, counter or decline with exact numbers.","lower-price":"Decide whether to lower price, refresh, relist, bundle, part out or hold. Ask for missing listing age or interest data rather than guessing.",profit:"Calculate final sale profit, profit per hour, ROI and total investment from saved numbers. Ask for missing numbers instead of guessing."};
export function buildQuickActionPrompt(item,action,settings=DEFAULT_SETTINGS){const request=ACTION_REQUESTS[action]||"Help me make the most practical next decision for this flip.";const f=calculateFinancials(item);return `You are inside Flip Finder AI. ${request}

MY RULES: minimum profit ${formatMoney(settings.minimumProfit)}, preferred ${formatMoney(settings.targetProfit)}, minimum hourly ${formatMoney(settings.minimumHourly)}, preferred ${formatMoney(settings.targetHourly)}, maximum investment ${formatMoney(settings.maxInvestment)}, balanced risk, PEI market.
ITEM: ${cleanText(item.name||item.analysis?.suggestedName)} | ${cleanText(item.category||item.analysis?.category)} | ${cleanText(item.source)} | asking ${formatMoney(item.askingPrice)} | purchase ${item.purchasePrice===""?"not purchased":formatMoney(item.purchasePrice)}
CURRENT NUMBERS: expected investment ${formatMoney(f.expectedInvestment)}, conservative resale ${formatMoney(f.resaleLow)}–${formatMoney(f.resaleHigh)}, conservative net ${formatMoney(f.expectedNetLow)}, estimated hourly ${f.expectedProfitPerHour==null?"unknown":formatMoney(f.expectedProfitPerHour)}.
SAVED AI REPORT: ${JSON.stringify(item.analysis||{})}
Answer directly and practically. If information is missing, say exactly what is missing. Never invent local sold prices or facts.`;}
export function extractAnalysisJson(output){if(!output)throw new Error("The AI returned no evaluation.");let text=String(output).trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"");const first=text.indexOf("{"),last=text.lastIndexOf("}");if(first>=0&&last>first)text=text.slice(first,last+1);try{const parsed=JSON.parse(text);if(!parsed||typeof parsed!=="object")throw new Error();return parsed;}catch{throw new Error("The AI response was not in the expected format. Try the evaluation again.");}}
